import os 
from dotenv import load_dotenv

load_dotenv()

DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")
DB_ENDPOINT = f'mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'

CONST_STRING_LENGTH = 128
CONST_TOKEN_LENGTH = 2048
CONST_PARAGRAPH_LENGTH = 4096

DEVCONNECT_ISSUER_URL = os.getenv('DEVCONNECT_ISSUER_URL')
DEVCONNECT_CLIENT_ID = os.getenv('DEVCONNECT_CLIENT_ID')
DEVCONNECT_CLIENT_SECRET = os.getenv('DEVCONNECT_CLIENT_SECRET')


