"""changed models

Revision ID: 220e4a7d9ce9
Revises: 70cd21f2b3af
Create Date: 2023-05-17 00:49:32.341282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220e4a7d9ce9'
down_revision = '70cd21f2b3af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
