"""changed models

Revision ID: 293ae482dc5e
Revises: f50fc4613c46
Create Date: 2023-05-17 00:17:05.817476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293ae482dc5e'
down_revision = 'f50fc4613c46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
