"""upadted models

Revision ID: 2d266100f8cb
Revises: 765c2a6a407a
Create Date: 2023-05-19 22:21:50.752341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d266100f8cb'
down_revision = '765c2a6a407a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_results', 'uptime_last_hour',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('report_results', 'downtime_last_hour',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('report_results', 'uptime_last_day',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('report_results', 'downtime_last_day',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('report_results', 'uptime_last_week',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('report_results', 'downtime_last_week',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_results', 'downtime_last_week',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('report_results', 'uptime_last_week',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('report_results', 'downtime_last_day',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('report_results', 'uptime_last_day',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('report_results', 'downtime_last_hour',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('report_results', 'uptime_last_hour',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
