"""changed models

Revision ID: 33f5b4840dca
Revises: edef19d6d55b
Create Date: 2023-05-17 02:22:15.171799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f5b4840dca'
down_revision = 'edef19d6d55b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
