"""changed models

Revision ID: 49470eea4cfa
Revises: 8283c76f44a7
Create Date: 2023-05-17 00:38:45.485802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49470eea4cfa'
down_revision = '8283c76f44a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
