"""changed models

Revision ID: 4967b71319d4
Revises: 293ae482dc5e
Create Date: 2023-05-17 00:23:12.455710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4967b71319d4'
down_revision = '293ae482dc5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
