"""changed models

Revision ID: 70cd21f2b3af
Revises: 49470eea4cfa
Create Date: 2023-05-17 00:48:16.290736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70cd21f2b3af'
down_revision = '49470eea4cfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
