"""added report models

Revision ID: 765c2a6a407a
Revises: 9647e595ade5
Create Date: 2023-05-19 18:12:01.338998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765c2a6a407a'
down_revision = '9647e595ade5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_results',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('uptime_last_hour', sa.Integer(), nullable=False),
    sa.Column('downtime_last_hour', sa.Integer(), nullable=False),
    sa.Column('uptime_last_day', sa.Integer(), nullable=False),
    sa.Column('downtime_last_day', sa.Integer(), nullable=False),
    sa.Column('uptime_last_week', sa.Integer(), nullable=False),
    sa.Column('downtime_last_week', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('report_id', 'store_id', 'uptime_last_hour', 'downtime_last_hour', 'uptime_last_day', 'downtime_last_day', 'uptime_last_week', 'downtime_last_week')
    )
    op.create_table('report_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_status')
    op.drop_table('report_results')
    # ### end Alembic commands ###
