"""changed models

Revision ID: 8283c76f44a7
Revises: ffb631ed1640
Create Date: 2023-05-17 00:37:45.529347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8283c76f44a7'
down_revision = 'ffb631ed1640'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
