"""changed models

Revision ID: 9647e595ade5
Revises: 33f5b4840dca
Create Date: 2023-05-17 02:22:48.653300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9647e595ade5'
down_revision = '33f5b4840dca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores_status',
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('store_id', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stores_status')
    # ### end Alembic commands ###
