"""changed models

Revision ID: b424586e4adb
Revises: 220e4a7d9ce9
Create Date: 2023-05-17 00:49:44.303953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b424586e4adb'
down_revision = '220e4a7d9ce9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_hours', sa.Column('end_time_asdfasdlocal', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_hours', 'end_time_asdfasdlocal')
    # ### end Alembic commands ###
