"""changed models

Revision ID: e391dba290fe
Revises: f12fe169e90f
Create Date: 2023-05-17 02:03:52.939449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e391dba290fe'
down_revision = 'f12fe169e90f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('stores_status',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('store_id', 'timestamp')
    )
    op.create_table('time_zone',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('store_id', sa.String(length=128), nullable=False),
    sa.Column('time_zone', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('store_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_zone')
    op.drop_table('stores_status')
    op.drop_table('store')
    # ### end Alembic commands ###
