"""changed models

Revision ID: edef19d6d55b
Revises: e391dba290fe
Create Date: 2023-05-17 02:05:18.261760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edef19d6d55b'
down_revision = 'e391dba290fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_hours', 'created_at')
    op.drop_column('business_hours', 'updated_at')
    op.drop_column('store', 'created_at')
    op.drop_column('store', 'updated_at')
    op.drop_column('stores_status', 'created_at')
    op.drop_column('stores_status', 'updated_at')
    op.drop_column('time_zone', 'created_at')
    op.drop_column('time_zone', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_zone', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False))
    op.add_column('time_zone', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
    op.add_column('stores_status', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False))
    op.add_column('stores_status', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
    op.add_column('store', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False))
    op.add_column('store', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
    op.add_column('business_hours', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False))
    op.add_column('business_hours', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
    # ### end Alembic commands ###
